sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run build-ci
before_deploy:
  - cd dist/ui-absolute
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: UI-Absolute/UIAbsolute
